# ----------------------------------------------------------------------------
#
# Package             : reflections
# Source Repo         : https://github.com/ronmamo/reflections
# Travis Job Link     : https://travis-ci.com/github/santosh653/reflections
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
arch:
  - amd64
  - ppc64le
language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
